In [ ]:
# Load libraries
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [ ]:
df= pd.read_csv("/content/Train.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (85) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
df.head()

Unnamed..0                               Flow.ID  ... Inbound       Label
0        1110  172.16.0.5-192.168.50.1-872-45984-17  ...       1  DrDoS_LDAP
1       25998  172.16.0.5-192.168.50.1-867-39632-17  ...       1  DrDoS_LDAP
2       10751    172.16.0.5-192.168.50.1-818-826-17  ...       1  DrDoS_LDAP
3       15983  172.16.0.5-192.168.50.1-894-32984-17  ...       1  DrDoS_LDAP
4       29733  172.16.0.5-192.168.50.1-877-12571-17  ...       1  DrDoS_LDAP

[5 rows x 88 columns]

In [ ]:
df.Label.unique()

array(['DrDoS_LDAP', 'DrDoS_DNS', 'DrDoS_MSSQL', 'DrDoS_UDP',
       'DrDoS_NetBIOS', 'Syn', 'UDP-lag', 'DrDoS_SSDP', 'DrDoS_SNMP',
       'DrDoS_NTP', 'TFTP', 'BENIGN'], dtype=object)

In [ ]:
df1 = df.replace(to_replace ="DrDoS_LDAP", 
                 value =1.0) 
df2 = df1.replace(to_replace ="DrDoS_DNS", 
                 value =2.0)
df3 = df2.replace(to_replace ="DrDoS_MSSQL", 
                 value =3.0)
df4 = df3.replace(to_replace ="DrDoS_UDP", 
                 value =4.0)
df5 = df4.replace(to_replace ="DrDoS_NetBIOS", 
                 value =5.0)
df6 = df5.replace(to_replace ="Syn", 
                 value =6.0)
df7 = df6.replace(to_replace ="UDP-lag", 
                 value =7.0)
df8 = df7.replace(to_replace ="DrDoS_SSDP", 
                 value =8.0)
df9 = df8.replace(to_replace ="DrDoS_SNMP", 
                 value =9.0)
df10 = df9.replace(to_replace ="DrDoS_NTP", 
                 value =10.0)
df11 = df10.replace(to_replace ="TFTP", 
                 value =11.0)
df12 = df11.replace(to_replace ="BENIGN", 
                 value =0.0)

In [ ]:
df12.Label.unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  0.])

In [ ]:
df12["Flow.ID"] = df12["Flow.ID"].str.replace(r'\D', '')
df12["Source.IP"] = df12["Source.IP"].str.replace(r'\D', '')
df12["Destination.IP"] = df12["Destination.IP"].str.replace(r'\D', '')
df12["Timestamp"] = df12["Timestamp"].str.replace(r'\D', '')
df13 = df12.drop(columns=['SimillarHTTP'])
df14 =  df13.replace([np.inf, -np.inf], np.nan)
df15 = df14.fillna(0)


In [ ]:
df15.dtypes

Unnamed..0          int64
Flow.ID            object
Source.IP          object
Source.Port         int64
Destination.IP     object
                   ...   
Idle.Std          float64
Idle.Max          float64
Idle.Min          float64
Inbound             int64
Label             float64
Length: 87, dtype: object

In [ ]:
df15.isnull().values.any()

False

In [ ]:
a = df15.drop('Label', axis=1)
b = df15['Label']

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif


In [ ]:
bestfeatures = SelectKBest(score_func=f_classif, k=10)
fit = bestfeatures.fit(a,b)

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:114: UserWarning: Features [38 39 40 50 53 57 63 64 65 66 67 68] are constant.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


In [ ]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(a.columns)

In [ ]:
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns

In [ ]:
featureScores

Specs          Score
0       Unnamed..0   51955.707092
1          Flow.ID      52.720401
2        Source.IP    1717.360103
3      Source.Port   79216.760878
4   Destination.IP    3533.308104
..             ...            ...
81       Idle.Mean    2475.944810
82        Idle.Std    1223.552055
83        Idle.Max    2454.288515
84        Idle.Min    2337.354451
85         Inbound  130658.003285

[86 rows x 2 columns]

In [ ]:
print(featureScores.nlargest(15,'Score'))  #print 10 best features

                     Specs          Score
59     Average.Packet.Size  325735.207411
45       Min.Packet.Length  318628.599899
14   Fwd.Packet.Length.Min  316318.509561
15  Fwd.Packet.Length.Mean  316218.336716
60    Avg.Fwd.Segment.Size  316218.336716
47      Packet.Length.Mean  298842.410780
13   Fwd.Packet.Length.Max  186568.966365
85                 Inbound  130658.003285
54          ACK.Flag.Count  118559.688229
6                 Protocol  109661.807224
3              Source.Port   79216.760878
21            Flow.Bytes.s   67861.143626
46       Max.Packet.Length   58679.169921
0               Unnamed..0   51955.707092
7                Timestamp   38137.974438


In [ ]:
myl = featureScores.nlargest(20,'Score')['Specs']

In [ ]:
X = df15[myl]
y = df15['Label']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[6009    0    0    0    1    0    0    0    0    0    0    1]
 [   0 5935    0    0    1    0    0    0   11   34    0    0]
 [   0    0 5767    0    0    0    0    4    0  201    1    0]
 [   0    0    0 5978    0    0    0    0    0    0    1    0]
 [   0    0    1    2 5950    1    0    0    0    0    0    0]
 [   0    0    0    1    1 5993    0    0    0    0    0    1]
 [   0    0    0    0    0    0 5979    0    1    0    0    0]
 [   0    0    1    0    1    0    0 6038    0    4    1    0]
 [   0   15    0    2    0    0    0    0 5962    0    0    0]
 [   1   39  164    0    1    0    0    4    1 5852    0    0]
 [   1    2    1    0    0    0    0    0    0    0 5953    0]
 [   2    0    0    5    0    0    0    0    0    0    1 6075]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      6011
         1.0       0.99      0.99      0.99      5981
         2.0       0.97      0.97      0.97      5973
         3.0       1.00   